name: Publish new version

on:
  push:
    branches:
      - "main"

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.18.2
          cache: "yarn"

      - name: Set variables
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.H3_NPM_TOKEN }}" >> .npmrc
          echo "@h3aven-labs:registry=https://npm.pkg.github.com/" >> .npmrc
          echo "PACKAGE_VERSION=$(cat package.json | jq -r .version)" >> $GITHUB_ENV

      - name: Deploy
        run: |
          yarn install
          yarn build
          npm publish

      - name: Tags
        run: |
          git tag v${{ env.PACKAGE_VERSION }}
          git push --tags
